[package]
name = "CRYPT"
version = "0.1.0"
edition = "2021"
authors = ["Dhruv Malpani <dhruv.malpani2005@gmail.com>", "", ""]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
